apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resnet-cifar-infer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resnet-cifar-infer
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
